### ISSUE TITLE
No Admin-client pem file

### ISSUE THREAD

**Issue by baabhu** [joynal/mongodb-sample-cluster#1]
Hello, 

Thanks for providing easy solution on x.509 authentication. It took a while to align the code and initial setup of the keys. Where as simple write up could have saved my time. No complains. Brilliant script. To test authentication on a shard cluster in minutes. 

Also the init-shard.sh mentioned about admin-client.pem. There were no mention about this pem file anywhere. 

And certificate.pem is also not mentioned. I renamed the client.pem to certificate.pem. 

I copied the 
certificate.pem to admin-client.pem. 

If you have write about these things it will be simple execution of bash scripts. 

Thanks again for the scripts.

**Comment by joynal** [comment]
@baabhu Sorry for the late response didn't notice the issue. I forgot to add details about the certificates. Follow this article https://hackernoon.com/create-a-mongodb-sharded-cluster-with-ssl-enabled-dace56bc7a17
